csv_config:
    number_of_wheels: 4
    keys:
        - '%time'
        - 'field.commands0.setpoint1'
        - 'field.commands0.setpoint2'
        - 'field.sensors0.encoder_1'
        - 'field.sensors0.velocity_1'
        - 'field.sensors0.current_1_d'
        - 'field.sensors0.current_1_q'
        - 'field.sensors0.current_1_u'
        - 'field.sensors0.current_1_v'
        - 'field.sensors0.current_1_w'
        - 'field.sensors0.voltage_1'
        - 'field.sensors0.voltage_1_u'
        - 'field.sensors0.voltage_1_v'
        - 'field.sensors0.voltage_1_w'
        - 'field.sensors0.temperature_1'
        - 'field.sensors0.encoder_2'
        - 'field.sensors0.velocity_2'
        - 'field.sensors0.current_2_d'
        - 'field.sensors0.current_2_q'
        - 'field.sensors0.current_2_u'
        - 'field.sensors0.current_2_v'
        - 'field.sensors0.current_2_w'
        - 'field.sensors0.voltage_2'
        - 'field.sensors0.voltage_2_u'
        - 'field.sensors0.voltage_2_v'
        - 'field.sensors0.voltage_2_w'
        - 'field.sensors0.temperature_2'
        - 'field.sensors0.encoder_pivot'
        - 'field.sensors0.velocity_pivot'
        - 'field.sensors0.accel_x'
        - 'field.sensors0.accel_y'
        - 'field.sensors0.accel_z'
        - 'field.sensors0.gyro_x'
        - 'field.sensors0.gyro_y'
        - 'field.sensors0.gyro_z'
        - 'field.sensors0.temperature_imu'
        - 'field.sensors0.pressure'
        - 'field.sensors0.voltage_bus'
rosbag_config:
    number_of_wheels: 4
    data_topic: '/sw_ethercat_parser/data'
    event_topic: '/ropod/event'
    commands:
        - 'setpoint1'
        - 'setpoint2'
    sensors:
        - 'encoder_1'
        - 'velocity_1'
        - 'current_1_d'
        - 'current_1_q'
        - 'current_1_u'
        - 'current_1_v'
        - 'current_1_w'
        - 'voltage_1'
        - 'voltage_1_u'
        - 'voltage_1_v'
        - 'voltage_1_w'
        - 'temperature_1'
        - 'encoder_2'
        - 'velocity_2'
        - 'current_2_d'
        - 'current_2_q'
        - 'current_2_u'
        - 'current_2_v'
        - 'current_2_w'
        - 'voltage_2'
        - 'voltage_2_u'
        - 'voltage_2_v'
        - 'voltage_2_w'
        - 'temperature_2'
        - 'encoder_pivot'
        - 'velocity_pivot'
        - 'accel_x'
        - 'accel_y'
        - 'accel_z'
        - 'gyro_x'
        - 'gyro_y'
        - 'gyro_z'
        - 'temperature_imu'
        - 'pressure'
        - 'voltage_bus'
blackbox_config:
    number_of_wheels: 4
    default_data_collection: 'ros_sw_ethercat_parser_data'
    default_event_collection: 'ros_ropod_event'
    commands:
        - 'setpoint1'
        - 'setpoint2'
    sensors:
        - 'encoder_1'
        - 'velocity_1'
        - 'current_1_d'
        - 'current_1_q'
        - 'current_1_u'
        - 'current_1_v'
        - 'current_1_w'
        - 'voltage_1'
        - 'voltage_1_u'
        - 'voltage_1_v'
        - 'voltage_1_w'
        - 'temperature_1'
        - 'encoder_2'
        - 'velocity_2'
        - 'current_2_d'
        - 'current_2_q'
        - 'current_2_u'
        - 'current_2_v'
        - 'current_2_w'
        - 'voltage_2'
        - 'voltage_2_u'
        - 'voltage_2_v'
        - 'voltage_2_w'
        - 'temperature_2'
        - 'encoder_pivot'
        - 'velocity_pivot'
        - 'accel_x'
        - 'accel_y'
        - 'accel_z'
        - 'gyro_x'
        - 'gyro_y'
        - 'gyro_z'
        - 'temperature_imu'
        - 'pressure'
        - 'voltage_bus'
granger_tests:
    selected_variables:
        - 'setpoint1'
        - 'setpoint2'
        - 'encoder_1'
        - 'current_1_u'
        - 'current_1_v'
        - 'current_1_w'
        - 'voltage_1'
        - 'encoder_2'
        - 'current_2_u'
        - 'current_2_v'
        - 'current_2_w'
        - 'voltage_2'
        - 'encoder_pivot'
        - 'accel_x'
        - 'accel_y'
        - 'accel_z'
        - 'gyro_x'
        - 'gyro_y'
        - 'gyro_z'
        - 'voltage_bus'
        - 'pressure'
variable_units:
     {
    'setpoint1': 'Amp',
    'setpoint2': 'Amp',
    'encoder_1': 'rad',
    'velocity_1': 'rad/s',
    'current_1_d': 'A',
    'current_1_q': 'A',
    'current_1_u': 'A',
    'current_1_v': 'A',
    'current_1_w': 'A',
    'voltage_1': 'V',
    'voltage_1_u': 'V',
    'voltage_1_v': 'V',
    'voltage_1_w': 'V',
    'temperature_1': 'K',
    'encoder_2': 'rad',
    'velocity_2': 'rad/s',
    'current_2_d': 'A',
    'current_2_q': 'A',
    'current_2_u': 'A',
    'current_2_v': 'A',
    'current_2_w': 'A',
    'voltage_2': 'V',
    'voltage_2_u': 'V',
    'voltage_2_v': 'V',
    'voltage_2_w': 'V',
    'temperature_2': 'K',
    'encoder_pivot': 'rad',
    'velocity_pivot': 'rad/s',
    'accel_x': 'm/s^2',
    'accel_y': 'm/s^2',
    'accel_z': 'm/s^2',
    'gyro_x': 'rad/s',
    'gyro_y': 'rad/s',
    'gyro_z': 'rad/s',
    'temperature_imu': 'K',
    'pressure': 'Pa',
    'voltage_bus': 'V'
    }
