csv_config:
    number_of_wheels: 4
    keys:
        - '%time'
        - 'field.commands0.setpoint1'
        - 'field.commands0.setpoint2'
        - 'field.sensors0.encoder_1'
        - 'field.sensors0.velocity_1'
        - 'field.sensors0.current_1_d'
        - 'field.sensors0.current_1_q'
        - 'field.sensors0.current_1_u'
        - 'field.sensors0.current_1_v'
        - 'field.sensors0.current_1_w'
        - 'field.sensors0.voltage_1'
        - 'field.sensors0.voltage_1_u'
        - 'field.sensors0.voltage_1_v'
        - 'field.sensors0.voltage_1_w'
        - 'field.sensors0.temperature_1'
        - 'field.sensors0.encoder_2'
        - 'field.sensors0.velocity_2'
        - 'field.sensors0.current_2_d'
        - 'field.sensors0.current_2_q'
        - 'field.sensors0.current_2_u'
        - 'field.sensors0.current_2_v'
        - 'field.sensors0.current_2_w'
        - 'field.sensors0.voltage_2'
        - 'field.sensors0.voltage_2_u'
        - 'field.sensors0.voltage_2_v'
        - 'field.sensors0.voltage_2_w'
        - 'field.sensors0.temperature_2'
        - 'field.sensors0.encoder_pivot'
        - 'field.sensors0.velocity_pivot'
        - 'field.sensors0.accel_x'
        - 'field.sensors0.accel_y'
        - 'field.sensors0.accel_z'
        - 'field.sensors0.gyro_x'
        - 'field.sensors0.gyro_y'
        - 'field.sensors0.gyro_z'
        - 'field.sensors0.temperature_imu'
        - 'field.sensors0.pressure'
        - 'field.sensors0.voltage_bus'
rosbag_config:
    number_of_wheels: 4
    data_topic: '/sw_ethercat_parser/data'
    event_topic: '/ropod/event'
    commands:
        - 'setpoint1'
        - 'setpoint2'
    sensors:
        - 'encoder_1'
        - 'velocity_1'
        - 'current_1_d'
        - 'current_1_q'
        - 'current_1_u'
        - 'current_1_v'
        - 'current_1_w'
        - 'voltage_1'
        - 'voltage_1_u'
        - 'voltage_1_v'
        - 'voltage_1_w'
        - 'temperature_1'
        - 'encoder_2'
        - 'velocity_2'
        - 'current_2_d'
        - 'current_2_q'
        - 'current_2_u'
        - 'current_2_v'
        - 'current_2_w'
        - 'voltage_2'
        - 'voltage_2_u'
        - 'voltage_2_v'
        - 'voltage_2_w'
        - 'temperature_2'
        - 'encoder_pivot'
        - 'velocity_pivot'
        - 'accel_x'
        - 'accel_y'
        - 'accel_z'
        - 'gyro_x'
        - 'gyro_y'
        - 'gyro_z'
        - 'temperature_imu'
        - 'pressure'
        - 'voltage_bus'
granger_tests:
    selected_variables:
        - 'setpoint1'
        - 'setpoint2'
        - 'encoder_1'
        - 'current_1_u'
        - 'current_1_v'
        - 'current_1_w'
        - 'voltage_1'
        - 'encoder_2'
        - 'current_2_u'
        - 'current_2_v'
        - 'current_2_w'
        - 'voltage_2'
        - 'encoder_pivot'
        - 'accel_x'
        - 'accel_y'
        - 'accel_z'
        - 'gyro_x'
        - 'gyro_y'
        - 'gyro_z'
        - 'voltage_bus'
